~/github/french-disco/bedmapCoverage.sh ../bed5/E14_D0_WGBS_SEPE_raw_rmDup.CpG_report_mergeTwoStrands_x5.bed5 HiChIP_D0-4_peaks_129399_data.txt count
~/github/french-disco/bedmapCoverage.sh ../bed5/E14_D0_WGBS_SEPE_raw_rmDup.CpG_report_mergeTwoStrands_x5.bed5 HiChIP_D0-4_peaks_129399_data.txt mean
~/github/french-disco/bedmapCoverage.sh ../bed5/E14_D0_WGBS_SEPE_raw_rmDup.CpG_report_mergeTwoStrands_x5.bed5 HiChIP_D0-4_peaks_129399_data.txt echo-map-range
~/github/french-disco/bedmapCoverage.sh ../bed5/E14_D4_WGBS_SEPE_raw_rmDup.CpG_report_mergeTwoStrands_x5.bed5 HiChIP_D0-4_peaks_129399_data.txt count
~/github/french-disco/bedmapCoverage.sh ../bed5/E14_D4_WGBS_SEPE_raw_rmDup.CpG_report_mergeTwoStrands_x5.bed5 HiChIP_D0-4_peaks_129399_data.txt mean
~/github/french-disco/bedmapCoverage.sh ../bed5/E14_D4_WGBS_SEPE_raw_rmDup.CpG_report_mergeTwoStrands_x5.bed5 HiChIP_D0-4_peaks_129399_data.txt echo-map-range
~/github/french-disco/bedmapCoverage.sh ../bed5/E14_D7_WGBS_SEPE_raw_rmDup.CpG_report_mergeTwoStrands_x5.bed5 HiChIP_D0-4_peaks_129399_data.txt count
~/github/french-disco/bedmapCoverage.sh ../bed5/E14_D7_WGBS_SEPE_raw_rmDup.CpG_report_mergeTwoStrands_x5.bed5 HiChIP_D0-4_peaks_129399_data.txt mean
~/github/french-disco/bedmapCoverage.sh ../bed5/E14_D7_WGBS_SEPE_raw_rmDup.CpG_report_mergeTwoStrands_x5.bed5 HiChIP_D0-4_peaks_129399_data.txt echo-map-range
